# Generated by Django 6.0.4 on 2026-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID"),
        ),
    ]
